on:
  pull_request:
    paths-ignore:
      - "artifacts.yaml"
      - "concierge.yaml"
      - "spread.yaml"
      - "tests/integration/run/task.yaml"
      - ".github/workflows/build.yaml"
      - ".github/instructions/**"

concurrency:
  group: rtdworkflows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rtd-docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs_rtd.yaml@main
    secrets: inherit
    with:
      enable-sphinx-python-dependency-build-checks: false