name: Tests

on:
  pull_request:
    paths-ignore:
      - "artifacts.yaml"
      - "concierge.yaml"
      - "spread.yaml"
      - "tests/integration/run/task.yaml"
      - ".github/workflows/build.yaml"
      - ".github/instructions/**"
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: false
      self-hosted-runner-label: "edge"
