#!/bin/sh
# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

PGPASSWORD="${POSTGRESQL_DB_PASSWORD}" psql -h "${POSTGRESQL_DB_HOSTNAME}" -U "${POSTGRESQL_DB_USERNAME}" "${POSTGRESQL_DB_NAME}" -c "
CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(80) UNIQUE NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL
);"
